baseURL = "https://graceofboy.github.io"
languageCode = "en-us"
title = "graceofboy"
publishDir = "docs"
summaryLength = 10

theme = "jeffprod"
[permalinks]
	post = "/:year/:filename"
[taxonomies]
	tag = "tags"
	archive = "archives"